services:

  db:
    image: docker.io/library/postgres:13-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    restart: always
    networks:
      net:
        ipv4_address: 192.168.5.3
  
  cachet:
    image: docker.io/cachethq/docker:latest
    ports:
      - 8000:8000
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PREFIX=${DB_PREFIX}
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - APP_ENV=${APP_ENV:-production}
      - APP_URL=192.168.5.2:8000
      - APP_DEBUG=false
      - DEBUG=false
      - MAIL_DRIVER=${MAIL_DRIVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
    depends_on:
      - db
    restart: on-failure
    networks:
      net:
        ipv4_address: 192.168.5.2

  monitor:
    image: docker.io/mtakaki/cachet-url-monitor:latest
    environment:
      - CACHET_API=192.168.5.2:8000/api/v1
      - CACHET_DEV=false
      - CACHET_TOKEN=${CACHET_TOKEN}
    volumes:
      - ./monitor-config.yml:/usr/src/app/config/config.yml:ro
    depends_on:
      - cachet
    restart: on-failure
    networks:
      net:
        ipv4_address: 192.168.5.4

volumes:
  db:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
